export const FC = {
    // master switch 
    MODE_INSERVICE: true,
    MODE_RABBITMQ_DEBUG: false,
    MODE_REBROADCAST_ON: true,
    MODE_SYNC_BLOCK_ON: true,

    // difficulty inspector parameters
    ALPHA_INTERN: 0.3,
    ALPHA_INTERVIEW: 0.1,
    DEBUG_DIFFICULTY_INTERN: 0.005,
    DEBUG_NUM_INTERN_PROBLEMS: 5,
    DEBUG_NUM_INTERVIEW_PROBLEMS: 5,
    DEBUG_PERIOD_DAYOFF: 5,
    INITIAL_HASHRATE: 400,
    MEANTIME_INTERN: 20000,
    MEANTIME_INTERVIEW: 20000,
    NUM_DAYOFF_PROBLEMS: 1,
    NUM_INTERN_PROBLEMS: 20,
    NUM_INTERVIEW_PROBLEMS: 20,
    NUM_JOB_BUFFER: 10,
    PERIOD_DAYOFF: 150,
    TOLERANCE_MAX_SIGMA_INSPECTOR: 3,
    TOLERANCE_MIN_SIGMA_INSPECTOR: 0.001,

    // interval of operations
    INTEVAL_CANDIDATE_BLOCK: 10000,
    INTEVAL_COLLECT_POOL_DATA: 3000,
    INTEVAL_PATROL_BLACKLIST: 600000,
    INTEVAL_PAY_WAGES: 60000,
    INTEVAL_STRATUM_RELEASE_DATA: 10000,
    INTEVAL_UPDATE_LAST_BLOCK: 5000,

    // network and connections
    NUM_MAX_PEERS: 15,
    THRESHOLD_REJECT_IMCOMING: 10,
    THRESHOLD_MIN_HASHRATE: 30,
    THRESHOLD_BLACKLIST: 30,
    TIMEOUT_NETWORK_SOCKET: 4000,
    TIMEOUT_ONPACKET_DEFAULT: 4000,
    TIMEOUT_ONPACKET_LONG: 12000,
    TIMEOUT_ONPACKET_SHORT: 4000,
    TOLERANCE_WORKER_DISCONNECTION_TIME: 30000,

    // MongoDB collection name
    MONGO_BLACKLIST: "Blacklist",
    MONGO_DISCONNECTIONS: "Disconnections",
    MONGO_LAST_BLOCK: "LastBlock",
    MONGO_MINED_BLOCKS: "MinedBlocks",
    MONGO_MINERS: "Miners",
    MONGO_PAY_WAGES: "PayWages",
    MONGO_POOL_SUMMARY: "PoolSummary",
    MONGO_REWARD_BASE: "RewardBase",
    MONGO_WORKERS: "Workers",

    // banker parameters
    BANKER_TX_FEE: 0.1,
    BANKER_WALLET_FOUNDER: [""],
    BANKER_WALLET_FREEHYCON: "",
    BANKER_WALLET_FREEMINER: "",
    BANKER_WALLET_MNEMONIC: "",
    BANKER_WALLET_PASSPHRASE: "",
    FEE_INITIAL: 0.1,
    FEE_FINAL: 0.1,
    NUM_TXS_CONFIRMATIONS: 12,

    // RabbitMQ and MongoDB URL
    URL_MONGO_DEBUG: "mongodb://localhost:27017",
    URL_MONGO_SERVICE: "mongodb://127.0.0.1:27017",
    URL_RABBITMQ_DEBUG: "amqp://localhost",
    URL_RABBITMQ_SERVICE: "amqp://freehycon:freehycon@127.0.0.1",
}
